### ISSUE TITLE
how to use 

### ISSUE THREAD

**Issue by diverrrsion** [iw4p/proxy-scraper#11]

**Comment by iw4p** [comment]
You can read the **readme** file, **Usage** section.

**Comment by typemyname1** [comment]
C:\Users\personal\Desktop\proxy-scraper-master>python proxyScraper.py
Traceback (most recent call last):
  File "proxyScraper.py", line 6, in <module>
    import requests
ImportError: No module named requests


Can you tell me why is showing this...

**Comment by iw4p** [comment]
Hello, try python 3
https://itsmycode.com/importerror-no-module-named-requests/
