### ISSUE TITLE
Pip modules (beautiful soup)

### ISSUE THREAD

**Issue by USBBios** [iw4p/proxy-scraper#2]
beautiful soup 3 won't work we'll need to use soup4. If you could, update the whole proxy-scraper :D so we could use tha latest modules. Thank you!

**Comment by iw4p** [comment]
Hello,
In the code, I used bs4 and I had beautifulsoup4 4.8.1 installed on my OS, I just now change the requirement file to install **beautifulsoup4** instead of **BeautifulSoup** and it works fine, try again, and if you still had a problem tell me.
