### ISSUE TITLE
proxyscraper not coming up

### ISSUE THREAD

**Issue by typemyname1** [iw4p/proxy-scraper#21]
Microsoft Windows [Version 10.0.19044.1826]
(c) Microsoft Corporation. All rights reserved.

C:\Users\personal\Desktop\proxy-scraper-master>proxyChecker.py
Traceback (most recent call last):
  File "C:\Users\personal\Desktop\proxy-scraper-master\proxyChecker.py", line 120, in <module>
    check(file=args.list, timeout=args.timeout, method=args.proxy, site=args.site, verbose=args.verbose,
  File "C:\Users\personal\Desktop\proxy-scraper-master\proxyChecker.py", line 51, in check
    with open(file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output.txt'

C:\Users\personal\Desktop\proxy-scraper-master>proxyScraper.py
usage: proxyScraper.py [-h] -p PROXY [-o OUTPUT] [-v]
proxyScraper.py: error: the following arguments are required: -p/--proxy

C:\Users\personal\Desktop\proxy-scraper-master>

**Comment by iw4p** [comment]
Please read the README.md file carefully.
Use the proxy scraper like this:
`python3 proxyScraper.py -p http`
And use the proxy checker like this:
`python3 proxyChecker.py -t 20 -s google.com -l output.txt`
