### ISSUE TITLE
Cannot install aiohttp

### ISSUE THREAD

**Issue by CyberVictoryMan** [iw4p/proxy-scraper#22]
`ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\normalizer.exe' -> 'C:\\Python310\\Scripts\\normalizer.exe.deleteme'`
help

**Comment by itsamirhn** [comment]
What's your python version?
You need python >= 3.5 to install aiohttp.

**Comment by CyberVictoryMan** [comment]
I have 3.11 version. Shud I degrade or is there any other way to install both the versions
