### ISSUE TITLE
Can't run proxy scraper

### ISSUE THREAD

**Issue by silentSLICE** [iw4p/proxy-scraper#30]
When I try to run the proxy scraper after installing the requirements, i get this:
C:\Users\austi\Desktop\proxy-scraper-master>pip install -r requirements.txt
Requirement already satisfied: beautifulsoup4==4.11.1 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 1)) (4.11.1)
Requirement already satisfied: requests==2.27.1 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 2)) (2.27.1)
Requirement already satisfied: colorama==0.4.4 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 3)) (0.4.4)
Requirement already satisfied: urllib3==1.26.9 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 4)) (1.26.9)
Requirement already satisfied: httpx in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from -r requirements.txt (line 5)) (0.23.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4==4.11.1->-r requirements.txt (line 1)) (2.3.2.post1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 2)) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 2)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from requests==2.27.1->-r requirements.txt (line 2)) (2.10)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from httpx->-r requirements.txt (line 5)) (0.16.3)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from httpx->-r requirements.txt (line 5)) (1.5.0)
Requirement already satisfied: sniffio in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from httpx->-r requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from httpcore<0.17.0,>=0.15.0->httpx->-r requirements.txt (line 5)) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\austi\appdata\local\programs\python\python311\lib\site-packages (from httpcore<0.17.0,>=0.15.0->httpx->-r requirements.txt (line 5)) (3.6.2)

C:\Users\austi\Desktop\proxy-scraper-master>python proxyScraper.py -p http
C:\Users\austi\Desktop\proxy-scraper-master\proxyScraper.py:191: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()

Anyone run into this and fix it?? I need help

**Comment by iw4p** [comment]
Hi,

May I know the exact number of your python version?
