### ISSUE TITLE
Sources

### ISSUE THREAD

**Issue by SwordKing69** [iw4p/proxy-scraper#31]
Hii there I used this scraper and it was good but it will be more better if you please provide option to manually add sources for proxies.
Like different sources files http,socks4,socks5 so that we can have more proxies from our own desired url/website. 
Please look into this.

**Comment by novak5712** [comment]
why don't you add a regex for ip:port instead, saves you the trouble.

**Comment by iw4p** [comment]
> why don't you add a regex for ip:port instead, saves you the trouble.

Because I'm not just good at regex, :D kidding, but having a well-structured scraper is better than just using regex in my prospective. Regex is my last solution always. Do you think regex is a better option?

**Comment by novak5712** [comment]
Well, sure why not? it can barely mess with your well structured code as it only consists of 5-6 lines of extra code (for simpler terms), without requiring any fancy structuring to the code.

**Comment by iw4p** [comment]
Can be a good solution, but I have to test it. If you have time you can do a sample on your fork maybe? And we can check the time for doing benchmarks.

**Comment by novak5712** [comment]
sure thing, I'll let you know once i have done it

**Comment by iw4p** [comment]
Thank you!
