### ISSUE TITLE
ModuleNotFoundError: No module named 'httpx

### ISSUE THREAD

**Issue by C0LiSii0N** [iw4p/proxy-scraper#36]
Hi, when I try to execute the command `python3 proxyScraper.py -p http` I get `ModuleNotFoundError: No module named 'httpx'`, but it is installed, I installed both httpx[cli] and httpx but it won't work. When I type httpx in command prompt it does work, but when I try to import it in python, it doesn't

**Comment by yataxyz** [comment]
pip install httpx OR pip3 install httpx

For every module not found add pip install to the cmd

**Comment by typemyname1** [comment]
Have added all d modules the proxyscraper wont work still....

**Comment by Gooferball69** [comment]
I HAVE SAME ISSUE MAYBE ITS NOT ADDED TO THE PATH

**Comment by Gooferball69** [comment]
![image](https://github.com/iw4p/proxy-scraper/assets/104870012/abcda2f6-c7f2-4096-9eed-2a1be406db25)
LIKE WTF

**Comment by iw4p** [comment]
try install it using venv or pipx
also check [this](https://github.com/tiangolo/fastapi/discussions/9286)
