### ISSUE TITLE
run on replit?

### ISSUE THREAD

**Issue by SGdoeXRnaGhobmJiYm** [iw4p/proxy-scraper#8]
hey , i know its a dumb question but is there a way to run it on replit?

**Comment by iw4p** [comment]
Hello, I have never tested it on replit but I think yes, It'll work.
And also I don't recommend it, because you'll share your secrets keys on the cloud which should stay between you and your computer.

**Comment by zaxhodV2** [comment]
i have premium stuff so its private and uh i think basically like what language should i use?

**Comment by iw4p** [comment]
Read the README file for getting your keys from Telegram. after that, you only need to have python installed and install the package by pip.
