### ISSUE TITLE
Add codacy.com

### ISSUE THREAD

**Issue by hoopengo** [iw4p/proxy-scraper#9]
You can add this repository to codacy.com to get a bage like this [![Codacy Badge](https://app.codacy.com/project/badge/Grade/edc4dd44fbcc409ea924cf26d5dbfe66)](https://www.codacy.com/gh/hoopengo/leetcode_patterns/dashboard?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=hoopengo/leetcode_patterns&amp;utm_campaign=Badge_Grade)

**Comment by iw4p** [comment]
Thanks, Is it free? or 14 days trial and then $15 per month?

**Comment by hoopengo** [comment]
it's free for 14 day trial
